version: "1"
context:
  active-host: "hh480.us1.dbt.com"
  active-project: "70403103962159"
projects:
  - project-name: "FlightDataAnalysis"
    project-id: "70403103962159"
    account-name: "N/a"
    account-id: "70403103952922"
    account-host: "hh480.us1.dbt.com"
    token-name: "cloud-cli-7b63"
    token-value: "dbtu_4FMINNQ9JlgG-Fm26WjlC9XnsyjIoQwTRsVHIYBxsZtrhBVoOk"


